---
platform: linux
image_resource:
  type: docker-image
  source:
    #repository: springcloud/pipeline-base
    repository: 192.168.11.1:5000/local-base-pipeline
      #tag: "latest"
      #insecure_registries: [ "192.168.11.1:5000" ]

inputs:
  - name: version
  - name: tools
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - tools/concourse/tasks/generate-version.sh
