---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
    #repository: 10.0.0.133:5000/local-base-pipeline
    #tag: "latest"
    #insecure_registries: [ "10.0.0.133:5000" ]

inputs:
  - name: version
  - name: tools
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - tools/concourse/tasks/generate-version.sh
