---
platform: linux
image_resource:
  type: docker-image
  source:
    #repository: springcloud/pipeline-base
    repository: localhost:5000/local-base-pipeline

inputs:
  - name: version
  - name: tools
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - tools/concourse/tasks/generate-version.sh
